#!/usr/bin/env bash
# Set IFS to colon ':' to split fields in /etc/passwd
IFS=":"

# Open the /etc/passwd file for reading
while read -r username password uid gid user_info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
    echo
done < /etc/passwd

# Reset IFS to its default value
IFS=$' \t\n'

