#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
while [[ $hour -le 12 ]] && [[ $minute -le 59 ]]; do echo "$hour:$minute"; minute=$((minute + 1)); [[ $minute -gt 59 ]] && hour=$((hour + 1)) && minute=1; done`
